#test config file
http {
	server {
		listen localhost:8080;
		server_name localhost;
		root /html;
        location / {
            index  index.html index.htm;
        }

        error_page  /50x.html;
        error_page  500 502 503 504;
        location = /50x.html {
            root   /error_pages;
        }
	}
}