##### Configuration example ####

http{
# Server Block
    server {
        listen 8080;
        server_name www.test.com;

        # Root directory
        root /html;

        # Index files
        index index.html;

        location / {
            root /html;

            limit_except GET POST {
                deny all;
            }
        }

    }

}
