##### Configuration example ####

http{
# Server Block
    server {
        listen 8080;
        server_name www.incorrect.com;

        # Root directory
        root /html;

        # Index files
        index incorrect.html;

        autoindex on;

        location / {
            root /html;

            autoindex on;
            
            client_max_body_size 1540000000;

            error_page 404 /error_pages/404.html;
            error_page 405 /error_pages/405.html;
            error_page 500 502 503 /custom_50x.html;
            error_page 504 /error_pages/504.html;

            limit_except GET POST DELETE{
                deny all;
            }
        }

    }

    server {
        listen 8080;
        server_name www.correct.com;

        # Root directory
        root /html;

        # Index files
        index correct.html;

        autoindex on;

        location / {
            root /html;

            autoindex on;
            
            client_max_body_size 1540000000;

            error_page 404 /error_pages/404.html;
            error_page 405 /error_pages/405.html;
            error_page 500 502 503 /custom_50x.html;
            error_page 504 /error_pages/504.html;

            limit_except GET POST DELETE{
                deny all;
            }
        }

    }

}
