http{
# Server Block
    server {
        listen 8080;
        server_name www.websurfers.com;

        # Root directory
        root /html;

        location / {
            autoindex on;
            index index.html;

        }

        location /sub_dir/ {
            limit_except GET {
                deny all;
            }
            root /html;

            index index.html;
        }

        location /sub_dir/sub_sub_dir/ {
            limit_except GET {
                deny all;
            }
            root /html;

            index index.html;

        }

    }

}
