http{
# Server Block
    server {
        listen 8080;
        server_name www.websurfers.com;

        # Root directory
        root /html;

        location / {
            autoindex on;
            index index.html;

        }

        location /sub_dir/ {
            autoindex on;
            index sub_dir/index.html;

        }

        location /sub_dir/sub_sub_dir/ {
            autoindex on;
            index sub_dir/sub_sub_dir/index.html;

        }

    }

}
